.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DAILYSTRIPS 1 "June 25, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dailystrips \- view web comic strips more conveniently
.SH SYNOPSIS
.B dailystrips
.RI [ options ] " stripname" ...
.SH DESCRIPTION
This manual page documents briefly the
.B dailystrips
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
\fBdailystrips\fP is a Perl script that gathers online comic strips for more
convenient viewing.  When in normal mode, it creates an HTML page that
references the strips directly, and when in local mode, it also downloads
the images to your local disk.  In local mode, it is intended to be run from
cron, and for your own private use only \-\- redistribution of the images
may be illegal.
.SH COMIC STRIP DEFINITIONS
There are three files from which the definitions for comic strips can be
read (aside from that specified with the \-\-defs option, which is read
right after the one in /usr/share/dailystrips).  The shipped definition file
is in /usr/share/dailystrips/strips.def and is read first.  Next,
dailystrips reads the system-wide override file in /etc/dailystrips.defs
(unless \-\-nosystem is specified), which can hold an updated definition
file permitting up to date or locally-specific definitions without having to
upgrade the whole package.  Finally, the user's own override file in
~/.dailystrips.defs is read (unless \-\-nopersonal is used).  The last
definition read has precedence.  Updated strip definitions can be downloaded
at <http://dailystrips.sourceforge.net/download.html>.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the README file in
/usr/share/doc/dailystrips/.
.TP
.B \-h, \-\-help
Show summary of options
.TP
.B \-q, \-\-quiet
Turn off progress messages
.TP
.B \-\-verbose
Turns on extra progress information, overrides \-q
.TP
.B \-\-list
List available strips
.TP
.B \-\-random
Download a random strip
.TP
.B \-\-defs FILE
Use alternate strips definition file
.TP
.B \-\-nopersonal
Ignore ~/.dailystrips.defs
.TP
.B \-\-nosystem
Ignore system-wide definitions in /etc/dailystrips.defs
.TP
.B \-\-output FILE
Output HTML to FILE instead of STDOUT (does not apply to local mode)
.TP
.B \-\-lite
Output a reduced HTML page
.TP
.B \-\-stripnav
Add links for navigation within the page
.TP
.B \-\-titles STRING
Customize HTML output
.TP
.B \-l, \-\-local
Output HTML to file and save strips locally
.TP
.B \-\-noindex
Disable symlinking current page to index.html (local mode only)
.TP
.B \-a, \-\-archive
Generate archive.html as a list of all days (local mode only)
.TP
.B \-d, \-\-dailydir
Create a separate directory for each day's images (local mode only)
.TP
.B \-\-stripdir
Create a separate directory for each strip's images (local mode only)
.TP
.B \-s, \-\-save
If it appears that a particular strip has been downloaded, does not attempt
to re-download it (local mode only)
.TP
.B \-\-nostale
If a new strip is not available, displays an error in the HTML output
instead of showing the old image
.TP
.B \-\-nosymlinks
Do not use symlinks for day-to-day duplicates
.TP
.B \-\-date DATE
Use value DATE instead of local time (DATE is parsed by Date::Parse
function, not available on Win32)
.TP
.B \-\-avantgo
Format images for viewing with Avantgo on PDAs
.TP
.B \-\-basedir DIR
Work in specified directory instead of current directory (program will look
here for strip definitions, previous HTML files, etc. and save new files
here)
.TP
.B \-\-proxy host:port
Use specified HTTP proxy server (overrides environment proxy, if set)
.TP
.B \-\-proxyauth user:pass
Set username and password for proxy server
.TP
.B \-\-noenvproxy
Ignore the http_proxy environment variable, if set
.TP
.B \-\-nospaces
Remove spaces from image filenames (local mode only)
.TP
.B \-\-useragent "STRING"
Set User-Agent: header to STRING (default is none)
.TP
.B \-\-retries NUM
When downloading items, retry NUM times instead of default 3 times
.TP
.B \-\-clean NUM
Keep only the latest NUM days of files; remove all older files
.TP
.B \-v, \-\-version
Print version number
.SH SEE ALSO
README, README.DEFS.gz (to add strips to the database), and README.LOCAL
(for more details about 'local' operation) in /usr/share/doc/dailystrips/.
.SH AUTHOR
This manual page was written by Rene Weber
<rene_debmaint@public.e-mail.elvenlord.com>, for the Debian GNU/Linux system
(but may be used by others).
