.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DAILYSTRIPS-UPDATE "1" "June 25, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
dailystrips-update \- download updated dailystrips definitions
.SH SYNOPSIS
.B dailystrips-update
[\fIOPTIONS\fR] \fIDAYS\fR
.SH WARNING
This script is intended to use under the assumption that the development
version of strips.def is the latest and best.  Unfortunately, at the time
of this writing (August, 2007) upstream development seems to have ceased, so
using this script will likely result in a
.B more out-of-date
strips definiton than is included in the distribution.
.SH WARNING
Due to the above, as of November 2009,
.BR dailystrips-update
has been neutered to exit immediately on execution, and it is expected that
it will be removed in a future version of this package.
.SH DESCRIPTION
The
.BR dailystrips-update
script is provided to automatically retrieve updated strip definitions from
a central server, eliminating the need to manually download and install new
versions of the entire program.

It is recommened that the
.BR dailystrips-update
script be run before each execution of the main dailystrips program. The
.BR dailystrips-update
script has provisions to only check for updates if the current file has
reached a certain age, which maximizes efficiency and should allow users to
run the update script before each execution of dailystrips without
overtaxing the update server. 
.SH USAGE
Operation is straightforward. Simply execute
.BR dailystrips-update
and the updated definitions will be saved to ~/.dailystrips-updates.def,
which will automatically be loaded by the main dailystrips program.
.SH OPTIONS
.TP
.B \-q, \-\-quiet
Turn off progress messages         
.TP
.B \-v, \-\-verbose
Turn on extra progress information, overrides \-q
.TP
.B \-\-proxy host:port
Use specified HTTP proxy server (overrides environment proxy, if set)
.TP
.B \-\-proxyauth user:pass
Set username and password for proxy server
.TP
.B \-\-noenvproxy
Ignore the http_proxy environment variable, if set
.TP
.B \-\-retries NUM
When downloading items, make NUM attempts instead of only once
.TP
.B \-\-updates FILE
Save updates to FILE instead of ~/.dailystrips-updates.def
.TP
.B \-\-minage NUM
Skip downloading updates if local file is less than NUM seconds old
.TP
.B \-V, \-\-version
Print version number
.TP
.B \-h, \-\-help
Show summary of options
.SH "SEE ALSO"
.BR dailystrips (1)
.SH AUTHOR
This manual page was written by Rene Weber
<rene_debmaint@public.e-mail.elvenlord.com>, for the Debian GNU/Linux system
(but may be used by others).
